#!/usr/bin/php
<?php
$current_date_time = date('Y-m-d H:i');
$newTime = date("Y-m-d H:i",strtotime("+15 minutes", strtotime($current_date_time)));
$newsub = substr($newTime, 0, 10);
print("$current_date_time $newTime $newsub\n");
exit(0);
// print("php testing\n");
// $t1 = '2020-08-11 12:44:11';
// $t2 = '2019-08-12 23:45:12';
// $mx = max(array($t1, $t2));
// print("$mx\n");
$dt1 = new DateTime('2014-05-07 18:53:22', new DateTimeZone('America/New_York'));
$dt2 = new DateTime('2014-05-07 16:53:44', new DateTimeZone('America/New_York'));
echo max($dt1,$dt2)->format(DateTime::RFC3339) . PHP_EOL; // 2014-05-07T16:53:00+00:00
echo min($dt1,$dt2)->format(DateTime::RFC3339) . PHP_EOL; // 2014-05-07T18:53:00+03:00
echo min($dt1,$dt2)->format('Y-m-d G:i:s') . PHP_EOL; // 2014-05-07T18:53:00+03:00
// echo Date(max($dt1, $dt2), 'Y-m-d G:i:s');

$dt1 = "2014-05-07 18:53:22";
list($y1,$m1,$d1,$h1,$i1,$s1) = explode("-", strtr(strtr($dt1, " ", "-"), ":", "-"));

echo 'type of $y1 is ';
echo gettype($y1);
echo "\n";

$xx = explode("-", strtr(strtr($dt1, " ", "-"), ":", "-"));
$x = explode("-", strtr(strtr($dt1, " ", "-"), ":", "-"));
$y = array($y1,$m1,$d1,$h1,$i1,$s1);
echo "$y1,$m1,$d1,$h1,$i1,$s1\n";

echo "===================\n";

$today = date("Y-m-d H:i:s");
echo "$today\n";
$xoday = date("Y-m-d H:i:s", strtotime($dt1));
echo "$xoday\n";
echo strtotime($dt1);
echo "\n";

//print_r($x);
//print_r($y);
//print_r($xx);
//array($a1,$m1,$d1,$h1,$i1,$s1) = $xx;
//print($a1);

echo time();
echo "\n";
echo time() - strtotime("2020-11-30 11:50:00");
echo "\n";
echo date("Y-m-d H:i:s", time());
echo "\n";

