DROP FUNCTION IF EXISTS UTCtoNY;

DELIMITER $$

CREATE FUNCTION UTCtoNY(dt DATETIME) 
-- RETURNS CHAR(5)
RETURNS DATETIME
DETERMINISTIC
BEGIN
  DECLARE ret_val DATETIME;
  -- SELECT DATE_FORMAT(CONVERT_TZ(dt, 'UTC', 'AMERICA/New_York'), '%m-%d %H:%s') INTO ret_val;
  SELECT CONVERT_TZ(dt, 'UTC', 'AMERICA/New_York') INTO ret_val;
  RETURN ret_val;

END$$ 

DELIMITER ;